### ISSUE TITLE
MySQL: adjust Databasestructure

### ISSUE THREAD

**Issue by MiG247** [MiG247/SmartLockerServer#38]
~~Check **GogHox** Picture for needed data from the server.~~
> from the discussion turned out its ok.

## toDo

- Implement the Pictures to the Combo, maybe it'll be a better option to load a PNG file to the Server 
  in folder like ../picture and safe the url into the database.

**Comment by Aridhol94** [comment]
Solution: Pictures are saved as Base64 String on Longblob. The Android app has to get the Base64 String and transform it with the depending function into a photo again
