### ISSUE TITLE
Node.js: Authentication 

### ISSUE THREAD

**Issue by MiG247** [MiG247/SmartLockerServer#50]
# ~~toDo~~
As we don't want everybody to access to the orders we need a authentication system on the server.

### Check
- Jsonwebtoken
- Basic Auth
- Bearer Token
- Digest Auth
- OAuth 2.0

> OAuth 2.0 might be not suitable but you can also check that maybe I'm wrong on that.

**Comment by MiG247** [comment]
## Got a workaround 
the clerk gets only the locker_nr, comboID, combo_name and the pickup_time.

## But for future Project it's necessary to add a authentication system

**Comment by RM92-LA** [comment]
Recommendation: JSON Web Token

Generated it with: https://jwt.io/

**Comment by MiG247** [comment]
Authentication works through JSON Web Token.
to get one you have to login or make an order as User.
