### ISSUE TITLE
Databasemodel

### ISSUE THREAD

**Issue by MiG247** [MiG247/SmartLockerServer#7]
Model the Database and load your filemodels into /Documentation

**Comment by Aridhol94** [comment]
Screenshot or the Visual Pradigm data?

**Comment by MiG247** [comment]
Screenshot is fine

**Comment by Aridhol94** [comment]
done

**Comment by MiG247** [comment]
Database ain't finished. A table with all Lockers, Locker_id, PIN, Available needs to be implemented, a table with Orders, order_id, food, Locker_id, time and (optional) a table with time schedules, booked lockers.

**Comment by MiG247** [comment]
Database model is good enough to make our Project runnable.
