### ISSUE TITLE
The "/order/{orderID}" API have a mistake in example view.

### ISSUE THREAD

**Issue by GogHox** [MiG247/SmartLockerServer#75]
The JSON value have a key is "pin", but the example view is write "PIN". The key of example view should be lower case "pin".

Here is the example view:
``` json
{
  "id": "df7cca36-3d7a-40f4-8f06-ae03cc22f041",
  "combo_id": 21,
  "ordered_at": "1985-04-12T23:20:50Z",
  "pickup_time": "10:30",
  "served": "true = 1, false = 0",
  "locker_nr": 1002,
  "PIN": 6832
}
```

**Comment by MiG247** [comment]
It's should be UpperCase fixed that. Now its like in example view
